doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        # configure these for your database server
        host: postgres
        dbname: '%env(resolve:DB_NAME)%'
        user: '%env(resolve:DB_USER)%'
        password: '%env(resolve:DB_PASSWORD)%'
        driver: 'pdo_pgsql'

      mysql:
        # configure these for your database server
        host: mysql
        dbname: '%env(resolve:DB_NAME)%'
        user: '%env(resolve:DB_USER)%'
        password: '%env(resolve:DB_PASSWORD)%'
        driver: 'pdo_mysql'
  orm:
    default_entity_manager: default

    entity_managers:
      default:
        connection: default
        dql:
          string_functions:
            JSON_GET_TEXT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Postgresql\JsonGetText
            CAST: Oro\ORM\Query\AST\Functions\Cast
        mappings:
          Postgres:
            is_bundle: false
            type: attribute
            dir: '%kernel.project_dir%/src/Entity/Postgres'
            prefix: 'App\Entity\Postgres'
            alias: Postgres
      mysql:
        connection: mysql
        dql:
          string_functions:
            JSON_EXTRACT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonExtract
            JSON_SEARCH: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonSearch
            JSON_CONTAINS: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContains
        mappings:
          Mysql:
            is_bundle: false
            type: attribute
            dir: '%kernel.project_dir%/src/Entity/Mysql'
            prefix: 'App\Entity\Mysql'
            alias: Mysql