doctrine:
  dbal:
    default_connection: postgres
    connections:
      postgres:
        # configure these for your database server
        host: postgres
        dbname: '%env(resolve:DB_NAME)%'
        user: '%env(resolve:DB_USER)%'
        password: '%env(resolve:DB_PASSWORD)%'
        driver: 'pdo_pgsql'

      mysql:
        # configure these for your database server
        host: mysql
        dbname: '%env(resolve:DB_NAME)%'
        user: '%env(resolve:DB_USER)%'
        password: '%env(resolve:DB_PASSWORD)%'
        driver: 'pdo_mysql'
  orm:
    default_entity_manager: postgres

    entity_managers:
      postgres:
        connection: postgres
        mappings:
          Postgres:
            is_bundle: false
            type: attribute
            dir: '%kernel.project_dir%/src/Entity'
            prefix: 'App\Entity'
            alias: Postgres
      mysql:
        connection: mysql
        mappings:
          Mysql:
            is_bundle: false
            type: attribute
            dir: '%kernel.project_dir%/src/Entity'
            prefix: 'App\Entity'
            alias: Mysql