version: "3.8"
services:
  php:
    build:
      context: docker/images/php
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - app
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"

  postgres:
    image: postgres:14.1
    volumes:
      - ./docker/.data/postgresql:/var/lib/postgresql/data
    networks:
      - app
    ports:
      - "${DC_POSTGRES_PORT}:5432"
    command: [
      "postgres",
      "-c", "random_page_cost=1.1",
      "-c", "default_statistics_target=100",
      "-c", "effective_io_concurrency=200",
      "-c", "shared_buffers=4GB",
      "-c", "work_mem=2GB",
      "-c", "maintenance_work_mem=1GB",
      "-c", "effective_cache_size=11GB",
      "-c", "max_worker_processes=14",
      "-c", "max_parallel_workers_per_gather=4",
      "-c", "max_parallel_workers=14",
      "-c", "max_parallel_maintenance_workers=4",
    ]
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  mysql:
    image: mysql:8.0
    volumes:
      - ./docker/.data/mysql:/var/lib/mysql
    networks:
      - app
    ports:
      - "${DC_MYSQL_PORT}:3306"
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app
networks:
  app:
volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
